config/routes.rb
Rails.application.routes.draw do

 

  
  get 'comments/show'

  get 'comments/index'

  get 'profiles/show'

  get 'answer_comments/new'

  get 'answer_comments/show'

  get 'answer_comments/index'
  
  get 'quizzes' => 'quiz#index', as: :my_quizzes
  
  get "courses/:id/vote/:vote", to: 'courses#vote'

  

  get 'my_courses' => 'courses#my_courses', as: :my_courses
  
  get 'courses/:course_id/quiz/:quiz_id/pending_quizzes/' => 'pending_quizzes#index', as: :pending_quizzes
  
  devise_for :users, :controllers => {registrations:'registrations'}
  
   resources :quiz_results, :except => [:edit, :update, :destroy]
   
   resources :courses do
      resources :lessons do
        resources :comments, :except => [:edit, :update]
      end  
      
      resources :quiz, :except => [:index,:edit, :update] do
          resources :questions, :except => [:show, :edit, :update]
          resources :pending_quizzes, :except => [:destroy, :edit ,:update]
      end
   end
   
   
  
  
  
  
  root 'welcome#homepage'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/quiz_answer.rb
class QuizAnswer < ActiveRecord::Base
  belongs_to :pending_quiz, inverse_of: :quiz_answers
  belongs_to :question
  

end

app/controllers/quiz_answers_controller.rb
class QuizAnswersController < ApplicationController
  before_action :set_pending_quiz
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  
  def index
  end
  
  def new
    @answer = @pending_quiz.quiz_answers.build
  end
  
  def create
    @answer = @pending_quiz.quiz_answers.build(answer_params)
    
    if @answer.save
      redirect_to @pending_quiz
    else
      flash[:error] = @answer.errors
      render :template => "pending_quizzes/new"
    end
  end

  def show
  end

  def edit
  end
  
  def update
  end
  
  def destroy
    @answer.destroy
    redirect_to @pending_quiz
  end
  
  private
  
  def set_pending_quiz
    @pending_quiz = PendingQuiz.find(params[:pending_quiz_id])
  end
  
  def set_answer
    @answer = @pending_quiz.quiz_answers.find(params[:id])
  end
  
  
  def answer_params
    params.require(:quiz_answer).permit(:answer, :question_id, :pending_quiz_id)
  end
end

app/helpers/quiz_answers_helper.rb
module QuizAnswersHelper
end

app/views/quiz_answers/_form.html.erb
<%= form_for(@quiz_answer) do |f| %>
  <% if @quiz_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz_answer.errors.count, "error") %> prohibited this quiz_answer from being saved:</h2>

      <ul>
      <% @quiz_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quiz_answers/edit.html.erb
<h1>Editing Quiz Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz_answer %> |
<%= link_to 'Back', quiz_answers_path %>

app/views/quiz_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quiz Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quiz_answers.each do |quiz_answer| %>
      <tr>
        <td><%= link_to 'Show', quiz_answer %></td>
        <td><%= link_to 'Edit', edit_quiz_answer_path(quiz_answer) %></td>
        <td><%= link_to 'Destroy', quiz_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz answer', new_quiz_answer_path %>

app/views/quiz_answers/new.html.erb
<h1>New Quiz Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', quiz_answers_path %>

app/views/quiz_answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_quiz_answer_path(@quiz_answer) %> |
<%= link_to 'Back', quiz_answers_path %>