config/routes.rb
Rails.application.routes.draw do

 

  
  get 'comments/show'

  get 'comments/index'

  get 'profiles/show'

  get 'answer_comments/new'

  get 'answer_comments/show'

  get 'answer_comments/index'
  
  get 'quizzes' => 'quiz#index', as: :my_quizzes
  
  get "courses/:id/vote/:vote", to: 'courses#vote'

  

  get 'my_courses' => 'courses#my_courses', as: :my_courses
  
  get 'courses/:course_id/quiz/:quiz_id/pending_quizzes/' => 'pending_quizzes#index', as: :pending_quizzes
  
  devise_for :users, :controllers => {registrations:'registrations'}
  
   resources :quiz_results, :except => [:edit, :update, :destroy]
   
   resources :courses do
      resources :lessons do
        resources :comments, :except => [:edit, :update]
      end  
      
      resources :quiz, :except => [:index,:edit, :update] do
          resources :questions, :except => [:show, :edit, :update]
          resources :pending_quizzes, :except => [:destroy, :edit ,:update]
      end
   end
   
   
  
  
  
  
  root 'welcome#homepage'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  has_many :comments
  
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 200}
  validates :link, presence: true, format: {with: /(?:.be\/|\/watch\?v=|\/(?=p\/))([\w\/\-]+)/}
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  load_and_authorize_resource :except => [:create, :update]
  before_action :set_course
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  
  def index
  end
  
  def new
    @lesson = @course.lessons.new
  end
  
  def create
    @lesson = @course.lessons.build(lessons_params)
    
    if @lesson.save
      redirect_to @course
    else
      flash[:error] = @lesson.errors
      render :template => "courses/show"
    end
  end

  def show
  end

  def edit
  end
  
  def update
  end
  
  def destroy
    @lesson.destroy
    redirect_to @course
  end
  
  private
  
  def set_course
    @course = Course.find(params[:course_id])
  end
  
  def set_lesson
    @lesson = @course.lessons.find(params[:id])
  end
  
  def lessons_params
    params.require(:lesson).permit(:name,:description,:link)
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
    def embed(youtubeurl)
        
        youtube_id = parse_youtube youtubeurl
        content_tag(:iframe,nil, src: "//www.youtube.com/embed/#{youtube_id}", class: "embed-responsive-item")
    end
    
    def parse_youtube url
       regex = /(?:.be\/|\/watch\?v=|\/(?=p\/))([\w\/\-]+)/
       url.match(regex)[1]
    end
end

app/views/lessons/_edit.html.erb
<%= render 'form' %>

app/views/lessons/_form.html.erb
<%= form_for(:lesson) do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :description %><br>
<%= f.text_area :description %><br>
<%= f.label :link %><br>
<%= f.text_field :link %><br>
<%= f.submit "Add lesson" %>
<%end%>

app/views/lessons/_index.html.erb
<table class="table table-hover">
<thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Youtube link</th>
      </tr>
    </thead>
<% unless lessons.nil? %>
    <% lessons.each do |l| %>
    
    
        <tbody>
            <tr>
                <td><%= link_to l.name, course_lesson_path(:course_id => l.course.id, :id => l.id) %></td>
                <td><%= l.description %></td>
                <td><%= l.link %></td>
                <td><%= link_to "Delete lesson", course_lesson_path(@course, l), method: :delete %></td>
            </tr>
        </tbody>
    
    <%end%>
<% end %>
</table>

app/views/lessons/_new.html.erb
    <%= form_for(lesson, :url =>"/courses/#{lesson.course_id}/lessons") do |f| %>
    <% if !flash[:error].nil? %>
        <div id="error_explanation">
          <h2><%= pluralize(flash[:error].count, "error") %> prohibited this lesson from being saved:</h2>
    
          <ul>
          <% flash[:error].full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
     <% end %>
    <div class="form-grouped">
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name , class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description,  class: "form-control input-lg" %>
        </div>
        <div class="form-group">
            <%= f.label :link %>
            <%= f.text_field :link, class: "form-control" %>
        </div>
        <div class="text-center">
        <%= f.submit "Add lesson", class: "btn btn-default" %>
        </div>  
    </div>
    <%end%>

app/views/lessons/show.html.erb
<div class="container ">
    <div class="row">
           <div class="jumbotron">
            <div class="text-center">
                <h1><%= @lesson.course.name %>
                <h2><%= @lesson.name %></h2>
                <p><%= @lesson.description %></p>
            </div>
            </div> 
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="center-block extra-bottom-padding">
                <div class="embed-responsive embed-responsive-4by3">
                    <%= embed(@lesson.link) %>
                </div>
        </div>
    </div>
      <div class="text-center extra-bottom-padding">
                 <div class="btn-group">
                    <%= link_to "Back to course", @lesson.course, class: "btn btn-default" %>
                  <% unless @lesson.course.lessons.first == @lesson %>
                     <%= link_to "Previous lesson", course_lesson_path(@lesson.course, @lesson.course.lessons[@lesson.course.lessons.find_index(@lesson)-1]), class: "btn btn-default" %>
                 <% end %>
                 <% unless @lesson.course.lessons.last == @lesson %>
                    <%= link_to "Next lesson", course_lesson_path(@lesson.course, @lesson.course.lessons[@lesson.course.lessons.find_index(@lesson)+1]), class: "btn btn-default" %>
                <% else %>
                <% if can? :create, PendingQuiz %>
                  <%= link_to 'Start quiz', new_course_quiz_pending_quiz_path(@lesson.course, @lesson.course.quiz), class: "btn btn-default"%>
                 <% end %>
                <% end %>
                </div>
        </div>
        <div class="row extra-bottom-padding">
            <%= render :partial => 'comments/index', :locals => {:comments => @lesson.comments.all} %>
            <% if user_signed_in? %>
            <%= render :partial => 'comments/new', :locals => {:comment => @lesson.comments.new(:lesson_id => @lesson.id)} %>
            <% end %>
        </div>
</div>