config/routes.rb
Rails.application.routes.draw do

 

  
  get 'comments/show'

  get 'comments/index'

  get 'profiles/show'

  get 'answer_comments/new'

  get 'answer_comments/show'

  get 'answer_comments/index'
  
  get 'quizzes' => 'quiz#index', as: :my_quizzes
  
  get "courses/:id/vote/:vote", to: 'courses#vote'

  

  get 'my_courses' => 'courses#my_courses', as: :my_courses
  
  get 'courses/:course_id/quiz/:quiz_id/pending_quizzes/' => 'pending_quizzes#index', as: :pending_quizzes
  
  devise_for :users, :controllers => {registrations:'registrations'}
  
   resources :quiz_results, :except => [:edit, :update, :destroy]
   
   resources :courses do
      resources :lessons do
        resources :comments, :except => [:edit, :update]
      end  
      
      resources :quiz, :except => [:index,:edit, :update] do
          resources :questions, :except => [:show, :edit, :update]
          resources :pending_quizzes, :except => [:destroy, :edit ,:update]
      end
   end
   
   
  
  
  
  
  root 'welcome#homepage'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource :except => [:create, :update]
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @number_of_votes = 0;
    @course.votes.each do |v|
    @number_of_votes+=v.value.to_i
    end
    if user_signed_in?
       if current_user.student?
        @can = false
        current_user.pending_quizzes.each do |pq|
          if pq.quiz.course == @course
            @can = true
          end
        end
       end
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def my_courses
    @courses = current_user.courses
  end
  
  def vote
    Vote.vote(params[:vote], current_user, @course)
		redirect_to course_path(@course)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description)
    end
    
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control input-lg" %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>
<div class="btn-group">
        <%= link_to 'Show', @course, class: "btn btn-default" %>
        <%= link_to 'Back', courses_path, class: "btn btn-default" %>
</div>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.user.name %></td>
        <td><%= link_to 'Show', course %></td>
        <% if can? :update, course %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <% end %>
        <% if can? :destroy, course %>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="btn-group">
  <% if can? :create, Course %>
  <%= link_to 'New Course', new_course_path, class: "btn btn-default" %>
  <% end %>
  <%= link_to 'Back', root_path, class: "btn btn-default"  %>
</div>

app/views/courses/my_courses.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing my courses</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.user.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, class: "btn btn-default" %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>
<%= link_to 'Back', courses_path, class: "btn btn-default" %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
  <p>
    <strong>Name:</strong>
    <%= @course.name %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= @course.description %>
  </p>
  
  <p>
    <strong>User:</strong>
    <%= @course.user.name %>
  </p>
  <div class="btn-group">
    <p>
    <strong>Votes:</strong> <%= @number_of_votes %>
    <% if @can %>
      <% if can? :vote, Course %>
      <%= link_to "+", "#{@course.id}/vote/for" , class: "btn btn-success" %>
      <% end %>
      <% if can? :vote, Course %>
      <%= link_to "-", "#{@course.id}/vote/against" , class: "btn btn-danger" %>
      <% end %>
    <% end %>
    </p>
  </div>
</div>

    <div class="row extra-bottom-padding">
          <div class="btn-group">
          <% if !@course.lessons.first.nil? %>
            <%= link_to "Watch course", course_lesson_path(@course, @course.lessons.first), class: "btn btn-default" %>
          <% else %>
            <div class="btn btn-warning">No lessons</div>
          <% end %>
          
          <% if @course.quiz.nil?%> 
            <% if can? :create, Quiz %>
            <%= link_to "Create quiz", course_quiz_index_path(:course_id => @course.id), method: :post, class: "btn btn-default" %>
            <% end %>
          <% else %>
            <% if can? :read, @course.quiz %>
            <%= link_to "Show quiz", course_quiz_path(@course, @course.quiz),  class: "btn btn-default" %>
            <% end %>
          <% end %>
    
          <% if can? :update, @course %>
          <%= link_to 'Edit', edit_course_path(@course),  class: "btn btn-default" %>
          <% end %>
          <%= link_to 'Back', courses_path ,  class: "btn btn-default"%>
          </div>
    </div>
    <% if can? :create, Lesson %>
      <% if @course.user == current_user %>
        <div class="row extra-bottom-padding">
          <%= render :partial => 'lessons/index', :locals => {:lessons => @course.lessons.all} %>
        </div>
        <div class="row">
          <%= render :partial => 'lessons/new', :locals => {:lesson => @course.lessons.new(:course_id => @course.id)} %>
        </div>
      <% end %>
    <% end %>
</div>  
    
      
  
      
  